config/routes.rb
Rails.application.routes.draw do

  resources :usuarios do
    resources :usuario_projetos do
      resources :registros do
        resources :comentarios do
          resources :anexos
        end
        resources :anexos
      end
    end
  end

  resources :projetos do
    resources :usuario_projetos do
      resources :registros do
        resources :comentarios do
          resources :anexos
        end
        resources :anexos
      end
    end
  end

  get 'contato' => 'contato#index'
  get 'equipe' => 'equipe#index'
  get 'sobre' => 'sobre#index'
  get 'termos' => 'termos#index'
  get 'sign_in' => "sign_in#index"

  root 'usuarios#new'

end

app/models/anexo.rb
class Anexo < ActiveRecord::Base
  belongs_to :registro
  belongs_to :comentario

  validates_presence_of :arquivo, :data_hora, :registro
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  belongs_to :registro
  belongs_to :usuario_projeto
  has_many :anexos

  validates_presence_of :texto_comentario, :data_hora, :registro, :usuario_projeto
end

app/models/projeto.rb
class Projeto < ActiveRecord::Base
  has_many :usuario_projetos
  has_many :usuarios, :through => :usuario_projetos

  validates_presence_of :descricao, :area, :status, :data_inicio
  validates_length_of :status, :in => 9..12
end

app/models/registro.rb
class Registro < ActiveRecord::Base
  belongs_to :usuario_projeto
  has_many :comentarios
  has_many :anexos

  validates_presence_of :data_hora, :resumo, :prioridade, :severidade, :status, :usuario_projeto
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  has_many :usuario_projetos
  has_many :projetos, :through => :usuario_projetos

  validates_presence_of :nome, :email, :senha
  validates_format_of :email, :with => /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates_uniqueness_of :email
end

app/models/usuario_projeto.rb
class UsuarioProjeto < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :projeto
  has_many :registros
  has_many :comentarios

  validates_presence_of :status, :usuario, :projeto
end

app/controllers/anexos_controller.rb
class AnexosController < ApplicationController
  before_action :set_anexo, only: [:show, :edit, :update, :destroy]

  # GET /anexos
  # GET /anexos.json
  def index
    @anexos = Anexo.all
  end

  # GET /anexos/1
  # GET /anexos/1.json
  def show
  end

  # GET /anexos/new
  def new
    @anexo = Anexo.new
  end

  # GET /anexos/1/edit
  def edit
  end

  # POST /anexos
  # POST /anexos.json
  def create
    @anexo = Anexo.new(anexo_params)

    respond_to do |format|
      if @anexo.save
        format.html { redirect_to @anexo, notice: 'Anexo was successfully created.' }
        format.json { render :show, status: :created, location: @anexo }
      else
        format.html { render :new }
        format.json { render json: @anexo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /anexos/1
  # PATCH/PUT /anexos/1.json
  def update
    respond_to do |format|
      if @anexo.update(anexo_params)
        format.html { redirect_to @anexo, notice: 'Anexo was successfully updated.' }
        format.json { render :show, status: :ok, location: @anexo }
      else
        format.html { render :edit }
        format.json { render json: @anexo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anexos/1
  # DELETE /anexos/1.json
  def destroy
    @anexo.destroy
    respond_to do |format|
      format.html { redirect_to anexos_url, notice: 'Anexo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anexo
      @anexo = Anexo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def anexo_params
      params.require(:anexo).permit(:arquivo, :registro_id, :comentario_id)
    end
end

app/controllers/equipe_controller.rb
class EquipeController < ApplicationController
  def index
  end
end

app/controllers/sobre_controller.rb
class SobreController < ApplicationController
  def index
  end
end

app/controllers/termos_controller.rb
class TermosController < ApplicationController
  def index
  end
end

app/controllers/usuario_projetos_controller.rb
class UsuarioProjetosController < ApplicationController
  before_action :set_usuario_projeto, only: [:show, :edit, :update, :destroy]

  # GET /usuario_projetos
  # GET /usuario_projetos.json
  def index
    @usuario_projetos = UsuarioProjeto.all
  end

  # GET /usuario_projetos/1
  # GET /usuario_projetos/1.json
  def show
  end

  # GET /usuario_projetos/new
  def new
    @usuario_projeto = UsuarioProjeto.new
  end

  # GET /usuario_projetos/1/edit
  def edit
  end

  # POST /usuario_projetos
  # POST /usuario_projetos.json
  def create
    @usuario_projeto = UsuarioProjeto.new(usuario_projeto_params)

    respond_to do |format|
      if @usuario_projeto.save
        format.html { redirect_to @usuario_projeto, notice: 'Usuario projeto was successfully created.' }
        format.json { render :show, status: :created, location: @usuario_projeto }
      else
        format.html { render :new }
        format.json { render json: @usuario_projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuario_projetos/1
  # PATCH/PUT /usuario_projetos/1.json
  def update
    respond_to do |format|
      if @usuario_projeto.update(usuario_projeto_params)
        format.html { redirect_to @usuario_projeto, notice: 'Usuario projeto was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario_projeto }
      else
        format.html { render :edit }
        format.json { render json: @usuario_projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuario_projetos/1
  # DELETE /usuario_projetos/1.json
  def destroy
    @usuario_projeto.destroy
    respond_to do |format|
      format.html { redirect_to usuario_projetos_url, notice: 'Usuario projeto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario_projeto
      @usuario_projeto = UsuarioProjeto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_projeto_params
      params.require(:usuario_projeto).permit(:status, :usuario_id, :projeto_id)
    end
end

app/helpers/anexos_helper.rb
module AnexosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/contato_helper.rb
module ContatoHelper
end

app/helpers/equipe_helper.rb
module EquipeHelper
end

app/helpers/projetos_helper.rb
module ProjetosHelper
end

app/helpers/registros_helper.rb
module RegistrosHelper
end

app/helpers/sign_in_helper.rb
module SignInHelper
end

app/helpers/sobre_helper.rb
module SobreHelper
end

app/helpers/termos_helper.rb
module TermosHelper
end

app/helpers/usuario_projetos_helper.rb
module UsuarioProjetosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuario_projetos/_form.html.erb
<%= form_for(@usuario_projeto) do |f| %>
  <% if @usuario_projeto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario_projeto.errors.count, "error") %> prohibited this usuario_projeto from being saved:</h2>

      <ul>
      <% @usuario_projeto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :usuario_id %><br>
    <%= f.text_field :usuario_id %>
  </div>
  <div class="field">
    <%= f.label :projeto_id %><br>
    <%= f.text_field :projeto_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuario_projetos/edit.html.erb
<h1>Editing Usuario Projeto</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario_projeto %> |
<%= link_to 'Back', usuario_projetos_path %>

app/views/usuario_projetos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Usuario Projetos</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Usuario</th>
      <th>Projeto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuario_projetos.each do |usuario_projeto| %>
      <tr>
        <td><%= usuario_projeto.status %></td>
        <td><%= usuario_projeto.usuario %></td>
        <td><%= usuario_projeto.projeto %></td>
        <td><%= link_to 'Show', usuario_projeto %></td>
        <td><%= link_to 'Edit', edit_usuario_projeto_path(usuario_projeto) %></td>
        <td><%= link_to 'Destroy', usuario_projeto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario projeto', new_usuario_projeto_path %>

app/views/usuario_projetos/new.html.erb
<h1>New Usuario Projeto</h1>

<%= render 'form' %>

<%= link_to 'Back', usuario_projetos_path %>

app/views/usuario_projetos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @usuario_projeto.status %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @usuario_projeto.usuario %>
</p>

<p>
  <strong>Projeto:</strong>
  <%= @usuario_projeto.projeto %>
</p>

<%= link_to 'Edit', edit_usuario_projeto_path(@usuario_projeto) %> |
<%= link_to 'Back', usuario_projetos_path %>