config/routes.rb
Rails.application.routes.draw do

  resources :usuarios do
    resources :usuario_projetos do
      resources :registros do
        resources :comentarios do
          resources :anexos
        end
        resources :anexos
      end
    end
  end

  resources :projetos do
    resources :usuario_projetos do
      resources :registros do
        resources :comentarios do
          resources :anexos
        end
        resources :anexos
      end
    end
  end

  get 'contato' => 'contato#index'
  get 'equipe' => 'equipe#index'
  get 'sobre' => 'sobre#index'
  get 'termos' => 'termos#index'
  get 'sign_in' => "sign_in#index"

  root 'usuarios#new'

end

app/models/anexo.rb
class Anexo < ActiveRecord::Base
  belongs_to :registro
  belongs_to :comentario

  validates_presence_of :arquivo, :data_hora, :registro
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  belongs_to :registro
  belongs_to :usuario_projeto
  has_many :anexos

  validates_presence_of :texto_comentario, :data_hora, :registro, :usuario_projeto
end

app/models/projeto.rb
class Projeto < ActiveRecord::Base
  has_many :usuario_projetos
  has_many :usuarios, :through => :usuario_projetos

  validates_presence_of :descricao, :area, :status, :data_inicio
  validates_length_of :status, :in => 9..12
end

app/models/registro.rb
class Registro < ActiveRecord::Base
  belongs_to :usuario_projeto
  has_many :comentarios
  has_many :anexos

  validates_presence_of :data_hora, :resumo, :prioridade, :severidade, :status, :usuario_projeto
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  has_many :usuario_projetos
  has_many :projetos, :through => :usuario_projetos

  validates_presence_of :nome, :email, :senha
  validates_format_of :email, :with => /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates_uniqueness_of :email
end

app/models/usuario_projeto.rb
class UsuarioProjeto < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :projeto
  has_many :registros
  has_many :comentarios

  validates_presence_of :status, :usuario, :projeto
end

app/controllers/anexos_controller.rb
class AnexosController < ApplicationController
  before_action :set_anexo, only: [:show, :edit, :update, :destroy]

  # GET /anexos
  # GET /anexos.json
  def index
    @anexos = Anexo.all
  end

  # GET /anexos/1
  # GET /anexos/1.json
  def show
  end

  # GET /anexos/new
  def new
    @anexo = Anexo.new
  end

  # GET /anexos/1/edit
  def edit
  end

  # POST /anexos
  # POST /anexos.json
  def create
    @anexo = Anexo.new(anexo_params)

    respond_to do |format|
      if @anexo.save
        format.html { redirect_to @anexo, notice: 'Anexo was successfully created.' }
        format.json { render :show, status: :created, location: @anexo }
      else
        format.html { render :new }
        format.json { render json: @anexo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /anexos/1
  # PATCH/PUT /anexos/1.json
  def update
    respond_to do |format|
      if @anexo.update(anexo_params)
        format.html { redirect_to @anexo, notice: 'Anexo was successfully updated.' }
        format.json { render :show, status: :ok, location: @anexo }
      else
        format.html { render :edit }
        format.json { render json: @anexo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anexos/1
  # DELETE /anexos/1.json
  def destroy
    @anexo.destroy
    respond_to do |format|
      format.html { redirect_to anexos_url, notice: 'Anexo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anexo
      @anexo = Anexo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def anexo_params
      params.require(:anexo).permit(:arquivo, :registro_id, :comentario_id)
    end
end

app/controllers/contato_controller.rb
class ContatoController < ApplicationController
  def index
  end
end

app/controllers/equipe_controller.rb
class EquipeController < ApplicationController
  def index
  end
end

app/controllers/registros_controller.rb
class RegistrosController < ApplicationController
  before_action :set_registro, only: [:show, :edit, :update, :destroy]

  # GET /registros
  # GET /registros.json
  def index
    @registros = Registro.all
  end

  # GET /registros/1
  # GET /registros/1.json
  def show
  end

  # GET /registros/new
  def new
    @registro = Registro.new
  end

  # GET /registros/1/edit
  def edit
  end

  # POST /registros
  # POST /registros.json
  def create
    @registro = Registro.new(registro_params)

    respond_to do |format|
      if @registro.save
        format.html { redirect_to @registro, notice: 'Registro was successfully created.' }
        format.json { render :show, status: :created, location: @registro }
      else
        format.html { render :new }
        format.json { render json: @registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registros/1
  # PATCH/PUT /registros/1.json
  def update
    respond_to do |format|
      if @registro.update(registro_params)
        format.html { redirect_to @registro, notice: 'Registro was successfully updated.' }
        format.json { render :show, status: :ok, location: @registro }
      else
        format.html { render :edit }
        format.json { render json: @registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registros/1
  # DELETE /registros/1.json
  def destroy
    @registro.destroy
    respond_to do |format|
      format.html { redirect_to registros_url, notice: 'Registro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registro
      @registro = Registro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registro_params
      params.require(:registro).permit(:data_hora, :resumo, :prioridade, :severidade, :status, :usuario_projeto_id)
    end
end

app/controllers/sobre_controller.rb
class SobreController < ApplicationController
  def index
  end
end

app/controllers/termos_controller.rb
class TermosController < ApplicationController
  def index
  end
end

app/helpers/anexos_helper.rb
module AnexosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/contato_helper.rb
module ContatoHelper
end

app/helpers/equipe_helper.rb
module EquipeHelper
end

app/helpers/projetos_helper.rb
module ProjetosHelper
end

app/helpers/registros_helper.rb
module RegistrosHelper
end

app/helpers/sign_in_helper.rb
module SignInHelper
end

app/helpers/sobre_helper.rb
module SobreHelper
end

app/helpers/termos_helper.rb
module TermosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/registros/_form.html.erb
<%= form_for(@registro) do |f| %>
  <% if @registro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@registro.errors.count, "error") %> prohibited this registro from being saved:</h2>

      <ul>
      <% @registro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data_hora %><br>
    <%= f.datetime_select :data_hora %>
  </div>
  <div class="field">
    <%= f.label :resumo %><br>
    <%= f.text_area :resumo %>
  </div>
  <div class="field">
    <%= f.label :prioridade %><br>
    <%= f.text_field :prioridade %>
  </div>
  <div class="field">
    <%= f.label :severidade %><br>
    <%= f.text_field :severidade %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :usuario_projeto_id %><br>
    <%= f.text_field :usuario_projeto_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/registros/edit.html.erb
<h1>Editing Registro</h1>

<%= render 'form' %>

<%= link_to 'Show', @registro %> |
<%= link_to 'Back', registros_path %>

app/views/registros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Registros</h1>

<table>
  <thead>
    <tr>
      <th>Data hora</th>
      <th>Resumo</th>
      <th>Prioridade</th>
      <th>Severidade</th>
      <th>Status</th>
      <th>Usuario projeto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registros.each do |registro| %>
      <tr>
        <td><%= registro.data_hora %></td>
        <td><%= registro.resumo %></td>
        <td><%= registro.prioridade %></td>
        <td><%= registro.severidade %></td>
        <td><%= registro.status %></td>
        <td><%= registro.usuario_projeto %></td>
        <td><%= link_to 'Show', registro %></td>
        <td><%= link_to 'Edit', edit_registro_path(registro) %></td>
        <td><%= link_to 'Destroy', registro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Registro', new_registro_path %>

app/views/registros/new.html.erb
<h1>New Registro</h1>

<%= render 'form' %>

<%= link_to 'Back', registros_path %>

app/views/registros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data hora:</strong>
  <%= @registro.data_hora %>
</p>

<p>
  <strong>Resumo:</strong>
  <%= @registro.resumo %>
</p>

<p>
  <strong>Prioridade:</strong>
  <%= @registro.prioridade %>
</p>

<p>
  <strong>Severidade:</strong>
  <%= @registro.severidade %>
</p>

<p>
  <strong>Status:</strong>
  <%= @registro.status %>
</p>

<p>
  <strong>Usuario projeto:</strong>
  <%= @registro.usuario_projeto %>
</p>

<%= link_to 'Edit', edit_registro_path(@registro) %> |
<%= link_to 'Back', registros_path %>